// Calibration test code generated by Atticus Terminal
// Plan:
// {
//   "export_style": "LemLib",
//   "drivetrain": "traction",
//   "imu": 1,
//   "tracking_wheels": 1,
//   "drive_error_source": "Tracking odom",
//   "profiles": [
//     "precise",
//     "normal",
//     "fast"
//   ],
//   "caps": [
//     0.5,
//     0.75,
//     1.0
//   ],
//   "drive_in": [
//     6.0,
//     24.0,
//     48.0
//   ],
//   "turn_deg": [
//     15.0,
//     45.0,
//     90.0
//   ],
//   "repeat": 6,
//   "auton_name": "Calibration Tests",
//   "auton_fn": "calibration_tests_auton"
// }

#include "main.h"
#include <cmath>
#include <cstdio>
#include <cstring>
#include "lemlib/api.hpp"

extern lemlib::Chassis chassis;

// Move/turn commands are generated from your current Export templates for this style.
// Define these macros to match your project (optional):
//   CAL_SET_PROFILE(name)         -> set drive profile
//   CAL_SET_DRIVE_CAP(volts)       -> set max drive voltage
//   CAL_SET_TURN_CAP(volts)        -> set max turn voltage
//   CAL_GET_POSE_X(), _Y(), _H()   -> return odom pose (in, in, deg)
//   CAL_SET_POSE(x, y, heading)    -> reset odom pose (if available)
#ifndef CAL_SET_PROFILE
#define CAL_SET_PROFILE(name) ((void)(name))
#endif
#ifndef CAL_SET_DRIVE_CAP
#define CAL_SET_DRIVE_CAP(volts) ((void)(volts))
#endif
#ifndef CAL_SET_TURN_CAP
#define CAL_SET_TURN_CAP(volts) ((void)(volts))
#endif
#ifndef CAL_GET_POSE_X
#define CAL_GET_POSE_X() 0.0
#endif
#ifndef CAL_GET_POSE_Y
#define CAL_GET_POSE_Y() 0.0
#endif
#ifndef CAL_GET_POSE_H
#define CAL_GET_POSE_H() 0.0
#endif
#ifndef CAL_SET_POSE
#define CAL_SET_POSE(x, y, heading) ((void)(x), (void)(y), (void)(heading))
#endif

// Auton selector hint:
//   Add {CAL_AUTON_NAME, calibration_tests_auton} to your auton list, or call calibration_tests_auton() in autonomous().
static const char* CAL_AUTON_NAME = "Calibration Tests";
static const bool CAL_HAS_SETPOS = true;
static const double CAL_PI = 3.141592653589793;
static double cal_last_target_x = 0.0;
static double cal_last_target_y = 0.0;
static double cal_last_target_heading = 0.0;
static int cal_last_timeout_ms = 0;
static double cal_drive_settle_err = 1.0;
static double cal_turn_settle_err = 1.0;
static int cal_drive_settle_time_ms = 120;
static int cal_turn_settle_time_ms = 120;
void cal_set_profile(const char* profile) { CAL_SET_PROFILE(profile); }
void cal_set_drive_cap(double volts) { CAL_SET_DRIVE_CAP(volts); }
void cal_set_turn_cap(double volts) { CAL_SET_TURN_CAP(volts); }
double cal_get_pose_x_in() { return CAL_GET_POSE_X(); }
double cal_get_pose_y_in() { return CAL_GET_POSE_Y(); }
double cal_get_heading_deg() { return CAL_GET_POSE_H(); }
void cal_set_pose(double x_in, double y_in, double heading_deg) {
  chassis.setPose(x_in, y_in, heading_deg);
}
static double cal_wrap_deg(double deg) {
  double out = std::fmod(deg, 360.0);
  if (out < 0) out += 360.0;
  return out;
}
static double cal_angle_error_deg(double target_deg, double current_deg) {
  double diff = std::fmod(target_deg - current_deg + 540.0, 360.0) - 180.0;
  return std::fabs(diff);
}
static int cal_drive_timeout_ms(double dist_in, double cap_frac) {
  double cap = cap_frac < 0.2 ? 0.2 : cap_frac;
  double ms = 500.0 + (std::fabs(dist_in) * 75.0) / cap;
  return (int)std::ceil(ms);
}
static int cal_turn_timeout_ms(double angle_deg, double cap_frac) {
  double cap = cap_frac < 0.2 ? 0.2 : cap_frac;
  double ms = 500.0 + (std::fabs(angle_deg) * 12.0) / cap;
  return (int)std::ceil(ms);
}
static double cal_drive_error_in(double target_x, double target_y) {
  double dx = cal_get_pose_x_in() - target_x;
  double dy = cal_get_pose_y_in() - target_y;
  return std::sqrt(dx * dx + dy * dy);
}
static double cal_turn_error_deg(double target_deg) {
  return cal_angle_error_deg(target_deg, cal_get_heading_deg());
}
static int cal_measure_settle_ms_drive(double target_x, double target_y, int start_ms, double err_in, int hold_ms, int max_ms) {
  int inside_ms = 0;
  while (inside_ms < hold_ms && (pros::millis() - start_ms) < max_ms) {
    double err = cal_drive_error_in(target_x, target_y);
    if (err <= err_in) inside_ms += 10; else inside_ms = 0;
    pros::delay(10);
  }
  return pros::millis() - start_ms;
}
static int cal_measure_settle_ms_turn(double target_deg, int start_ms, double err_deg, int hold_ms, int max_ms) {
  int inside_ms = 0;
  while (inside_ms < hold_ms && (pros::millis() - start_ms) < max_ms) {
    double err = cal_angle_error_deg(target_deg, cal_get_heading_deg());
    if (err <= err_deg) inside_ms += 10; else inside_ms = 0;
    pros::delay(10);
  }
  return pros::millis() - start_ms;
}
void cal_drive_to(double dist_in, double cap_frac) {
  double heading_deg = cal_get_heading_deg();
  double x_in = cal_get_pose_x_in();
  double y_in = cal_get_pose_y_in();
  double delta_deg = 0.0;
  if (CAL_HAS_SETPOS) {
    cal_set_pose(0.0, 0.0, 0.0);
    heading_deg = 0.0;
    x_in = dist_in;
    y_in = 0.0;
  } else {
    double rad = heading_deg * (CAL_PI / 180.0);
    x_in = x_in + dist_in * std::cos(rad);
    y_in = y_in + dist_in * std::sin(rad);
  }
  cal_last_target_x = x_in;
  cal_last_target_y = y_in;
  cal_last_target_heading = heading_deg;
  const bool forwards = dist_in >= 0.0;
  const double drive_max_v = cap_frac * 12.0;
  const double heading_max_v = cap_frac * 12.0;
  const double drive_settle_err = cal_drive_settle_err;
  const int drive_settle_time = cal_drive_settle_time_ms;
  int timeout_ms = cal_drive_timeout_ms(dist_in, cap_frac);
  cal_last_timeout_ms = timeout_ms;
  // Template: move
  chassis.moveToPoint(x_in, y_in, timeout_ms, {.forwards = forwards, .minSpeed = 0, .earlyExitRange = 0});
}
void cal_turn_to(double heading_deg, double cap_frac) {
  double delta_deg = heading_deg;
  double turn_mag = std::fabs(delta_deg);
  turn_mag = cal_angle_error_deg(heading_deg, cal_get_heading_deg());
  cal_last_target_heading = heading_deg;
  const double turn_max_v = cap_frac * 12.0;
  const double turn_settle_err = cal_turn_settle_err;
  const int turn_settle_time = cal_turn_settle_time_ms;
  int timeout_ms = cal_turn_timeout_ms(turn_mag, cap_frac);
  cal_last_timeout_ms = timeout_ms;
  // Template: turn_global
  chassis.turnToHeading(heading_deg, timeout_ms, {.minSpeed = 0, .earlyExitRange = 0});
}
static void cal_log(const char* move_type, const char* profile, double cap_frac,
                   double magnitude, double final_err, int settle_ms) {
  printf("{\"move_type\":\"%s\",\"profile\":\"%s\",\"cap_frac\":%.2f,",
         move_type, profile, cap_frac);
  if (std::strcmp(move_type, "drive") == 0) {
    printf("\"distance_in\":%.2f,", magnitude);
  } else {
    printf("\"angle_deg\":%.2f,", magnitude);
  }
  printf("\"final_err\":%.3f,\"settle_ms\":%d}\n", final_err, settle_ms);
}

void run_calibration_tests() {
  const char* profiles[] = {"precise", "normal", "fast"};
  const double caps[] = {0.50, 0.75, 1.00};
  const double drive_in[] = {6.00, 24.00, 48.00};
  const double turn_deg[] = {15.00, 45.00, 90.00};
  const int repeats = 6;
  const double drive_settle_err = 1.0;
  const double turn_settle_err = 1.0;
  const int settle_hold_ms = 120;
  cal_drive_settle_err = drive_settle_err;
  cal_turn_settle_err = turn_settle_err;
  cal_drive_settle_time_ms = settle_hold_ms;
  cal_turn_settle_time_ms = settle_hold_ms;
  const int profile_count = sizeof(profiles) / sizeof(profiles[0]);
  const int cap_count = sizeof(caps) / sizeof(caps[0]);
  const int drive_count = sizeof(drive_in) / sizeof(drive_in[0]);
  const int turn_count = sizeof(turn_deg) / sizeof(turn_deg[0]);

  for (int p = 0; p < profile_count; ++p) {
    cal_set_profile(profiles[p]);
    for (int c = 0; c < cap_count; ++c) {
      const double cap_frac = caps[c];
      const double cap_v = cap_frac * 12.0;
      for (int r = 0; r < repeats; ++r) {
        for (int i = 0; i < drive_count; ++i) {
          const double dist = drive_in[i];
          cal_set_drive_cap(cap_v);
          const int t0 = pros::millis();
          cal_drive_to(dist, cap_frac);
          const double tx = cal_last_target_x;
          const double ty = cal_last_target_y;
          const int settle_ms = cal_measure_settle_ms_drive(tx, ty, t0, drive_settle_err, settle_hold_ms, cal_last_timeout_ms + 1000);
          const double err = cal_drive_error_in(tx, ty);
          cal_log("drive", profiles[p], cap_frac, dist, err, settle_ms);
          pros::delay(120);
        }
        for (int i = 0; i < turn_count; ++i) {
          const double ang = turn_deg[i];
          if (CAL_HAS_SETPOS) {
            cal_set_pose(0.0, 0.0, 0.0);
          }
          cal_set_turn_cap(cap_v);
          const int t0 = pros::millis();
          cal_turn_to(ang, cap_frac);
          const double th = cal_last_target_heading;
          const int settle_ms = cal_measure_settle_ms_turn(th, t0, turn_settle_err, settle_hold_ms, cal_last_timeout_ms + 1000);
          const double err = cal_turn_error_deg(th);
          cal_log("turn", profiles[p], cap_frac, ang, err, settle_ms);
          pros::delay(120);
        }
      }
    }
  }
}

void calibration_tests_auton() {
  run_calibration_tests();
}
